### ISSUE TITLE
Villagers not trading dynamically, or at all once out of stock...

### ISSUE THREAD

**Issue by Gantros** [orlouge/DynamicVillagerTrades#1]
I really enjoyed this mod in 1.19.2, and was excited to use it again in my new 1.20.1 world, but I have observed an issue where the offerings do not change with any villager, only when ranking up. Furthermore, unless ranking up, a villager does not refresh their stock once exhausted, making it impossible to trade with them further once depleted. Here is a list of mods and other relevant information that I could gather:

MC v1.20,1
Forge v47.1.28

Mod List:
  [✔️]AdLods-1.20.1-8.1.0.0-build.0142.jar
  [✔️] AI-Improvements-1.20-0.5.2.jar
  [✔️] AirHop-v8.0.0-1.20.1-Forge.jar
  [✔️] alexsmobs-1.22.5.jar
  [✔️] almostunified-forge-1.20.1-0.5.0.jar
  [✔️] appleskin-forge-mc1.20.1-2.5.0.jar
  [✔️] architectury-9.1.10-forge.jar
  [✔️] balm-forge-1.20-7.0.4.jar
  [✔️] bettercombat-forge-1.7.2+1.20.1.jar
  [✔️] betterfpsdist-1.20.1-2.9.jar
  [✔️] better-respawn-forge-1.20.1-2.0.2.jar
  [✔️] betterspawnercontrol-1.20.1-4.2.jar
  [✔️] bigbrain-1.20-1.7.1.jar
  [✔️] Bookshelf-Forge-1.20.1-20.0.1.jar
  [✔️] BuildGuide-1.20-0.3.3.jar
  [✔️] canary-mc1.20(.1)-0.2.6.jar
  [✔️] carryon-forge-1.20.1-2.1.0.1.jar
  [✔️] catalogue-forge-1.20.1-1.7.1.jar
  [✔️] chalk-1.20.1-1.6.1.jar
  [✔️] charmofundying-forge-6.4.2+1.20.1.jar
  [✔️] chickensshed-1.4.0-0.jar
  [✔️] citadel-2.4.2-1.20.1.jar
  [✔️] cloth-config-11.0.99-forge.jar
  [✔️] Clumps-forge-1.20.1-12.0.0.3.jar
  [✔️] collective-1.20.1-6.65.jar
  [✔️] comforts-forge-6.3.3+1.20.1.jar
  [✔️] corpse-1.20.1-1.0.3.jar
  [✔️] create_jetpack-forge-4.0.0.jar
  [✔️] create-1.20.1-0.5.1.d.jar
  [✔️] cryingportals-1.20.1-2.3.jar
  [✔️] curios-forge-5.2.0-beta.3+1.20.1.jar
  [✔️] dismountentity-1.20.1-3.0.jar
  [✔️] domesticationinnovation-1.7.0-1.20.jar
  [✔️] dynamiclightsreforged-1.20.1_v1.5.0.jar
  [✔️] dynamicvillagertrades-1.3.0-forge.jar
  [✔️] EasyAnvils-v8.0.0-1.20.1-Forge.jar
  [✔️] EnchantmentDescriptions-Forge-1.20-16.0.1.jar
  [✔️] entityculling-forge-1.6.2-mc1.20.jar
  [✔️] ExplorersCompass-1.20.1-1.3.2-forge.jar
  [✔️] FallingTree-1.20.1-4.2.0.jar
  [✔️] FarmersDelight-1.20.1-1.2.2a.jar
  [✔️] ferritecore-6.0.0-forge.jar
  [✔️] flatbedrock-forge-3.0.0-build.17+mc1.20.1.jar
  [✔️] ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar
  [✔️] furnacerecycle-1.20.1-2.0.jar
  [✔️] geckolib-forge-1.20-4.2.jar
  [✔️] geophilic-v2.0.0-mc1.20u1.20.1.jar
  [✔️] gpumemleakfix-1.20.1-1.6.jar
  [✔️] grindstonesharpertools-1.20.1-3.1.jar
  [✔️] guifollowers-1.20.1-3.2.jar
  [✔️] hoetweaks-1.20.1-3.2.jar
  [✔️] hole_filler_mod-1.2.8_mc-1.20_forge.jar
  [✔️] Homeostatic-1.20.1-2.9.2.0.jar
  [✔️] horizontalreinforceddeepslate-1.20-1.0.1.jar
  [✔️] HorseExpert-v8.0.0-1.20.1-Forge.jar
  [✔️] InventoryProfilesNext-forge-1.20-1.10.6.jar
  [✔️] jei-1.20.1-forge-15.2.0.23.jar
  [✔️] Kiwi-1.20.1-forge-11.0.0.jar
  [✔️] kotlinforforge-4.4.0-all.jar
  [✔️] KryptonReforged-0.2.3.jar
  [✔️] libIPN-forge-1.20-3.0.2.jar
  [✔️] mcw-bridges-2.1.1-mc1.20.1forge.jar
  [✔️] mcw-fences-1.0.7-mc1.20.1forge.jar
  [✔️] mcw-lights-1.0.6-mc1.20.1forge.jar
  [✔️] mcw-paths-1.0.3forge-mc1.20.1.jar
  [✔️] mcw-roofs-2.2.4-mc1.20.1forge.jar
  [✔️] mcw-trapdoors-1.1.1-mc1.20.1forge.jar
  [✔️] memorysettings-1.20.1-5.2.jar
  [✔️] modernfix-forge-5.2.5+mc1.20.1.jar
  [✔️] moonlight-1.20-2.6.1-forge.jar
  [✔️] moveboats-1.20.1-3.0.jar
  [✔️] moveminecarts-1.20.1-3.2.jar
  [✔️] NaturesCompass-1.20.1-1.11.1-forge.jar
  [✔️] netherportalfix-forge-1.20-13.0.0.jar
  [✔️] NoSeeNoTick-2.0.0-1.20.1.jar
  [✔️] nutritiousmilk-1.20.1-3.1.jar
  [✔️] ornamental-1.20-4.12.78.jar
  [✔️] Patchouli-1.20.1-81-FORGE.jar
  [✔️] placeableblazerods-1.20.1-3.1.jar
  [✔️] player-animation-lib-forge-1.0.2-rc1+1.20.jar
  [✔️] polymorph-forge-0.49.0+1.20.1.jar
  [✔️] prettybeaches-forge-1.20-11.0.1.jar
  [✔️] PuzzlesLib-v8.0.7-1.20.1-Forge.jar
  [✔️] radiantgear-forge-2.1.0+1.20.1.jar
  [✔️] realisticbees-1.20.1-3.4.jar
  [✔️] redstonepen-1.20.1-forge-1.3.20.jar
  [✔️] rubidium_extras-1.20.1_v1.4.1.jar
  [✔️] rubidium-0.6.5.jar
  [✔️] scaffoldingdropsnearby-1.20.1-3.0.jar
  [✔️] seasonhud-1.20.1-1.4.20.jar
  [✔️] SereneSeasons-1.20.1-9.0.0.43.jar
  [✔️] smelting-plus-1.0.4(fabric-forge-quilt).jar
  [✔️] SnowRealMagic-1.20.1-forge-9.0.0.jar
  [✔️] solapplepie-1.20.1-2.3.0.jar
  [✔️] sophisticatedbackpacks-1.20.1-3.18.56.890.jar
  [✔️] sophisticatedcore-1.20.1-0.5.81.378.jar
  [✔️] spyglass_improvements-1.4+mc1.20+forge.jar
  [✔️] starlight-1.1.2+forge.1cda73c.jar
  [✔️] supplementaries-1.20-2.5.18.jar
  [✔️] TerraBlender-forge-1.20.1-3.0.0.169.jar
  [✔️] TextruesRubidiumOptions-1.0.0+mc1.20.jar
  [✔️] theoneprobe-1.20.1-10.0.1.jar
  [✔️] ToolBelt-1.20-1.20.0.jar
  [✔️] trashslot-forge-1.20-15.0.0.jar
  [✔️] undeco-1.20-1.3.7.jar
  [✔️] weakerspiderwebs-1.20.1-3.2.jar
  [✔️] Xaeros_Minimap_FP23.4.4_Forge_1.20.jar
  [✔️] XaerosWorldMap_1.30.6_Forge_1.20.jar
  [✔️] YungsApi-1.20-Forge-4.0.jar
  [✔️] YungsBetterDesertTemples-1.20-Forge-3.0.jar
  [✔️] YungsBetterDungeons-1.20-Forge-4.0.jar
  [✔️] YungsBetterJungleTemples-1.20-Forge-2.0.jar
  [✔️] YungsBetterMineshafts-1.20-Forge-4.0.jar
  [✔️] YungsBetterNetherFortresses-1.20-Forge-2.0.jar
  [✔️] YungsBetterOceanMonuments-1.20-Forge-3.0.jar
  [✔️] YungsBetterStrongholds-1.20-Forge-4.0.jar
  [✔️] YungsBetterWitchHuts-1.20-Forge-3.0.jar

**Comment by orlouge** [comment]
I can't reproduce this issue with DVT alone on the same version. I'm not familiar with many of those mods, try to find a smaller combination of mods that cause the issue, starting from the ones that may affect trades or villager behavior, or anything that changed from 1.19 to 1.20. Also check the logs for errors.

**Comment by DankestO** [comment]
Excuse me for getting into this issue (?
I wanted to help a little about this problem, which has already happened to me with other mods.

I have seen that you have Canary installed, this mod touches things on the villagers, and causes them to act strangely, like the one you mention not resupplying their trades.

Try deleting it to make sure it's that?

https://github.com/AbdElAziz333/Canary/issues/165#issuecomment-1646869893
As mentioned here, if it is the error that I mention, it is solved in the way that they explain there.
""Adding mixin.ai = false" to the config"
